# Generated by Django 3.1.7 on 2021-04-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('record_name', models.IntegerField(primary_key=True, serialize=False)),
                ('n_sig', models.CharField(blank=True, max_length=1000, null=True)),
                ('fs', models.CharField(blank=True, max_length=1000, null=True)),
                ('counter_freq', models.CharField(blank=True, max_length=1000, null=True)),
                ('base_counter', models.CharField(blank=True, max_length=1000, null=True)),
                ('sig_len', models.CharField(blank=True, max_length=1000, null=True)),
                ('base_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('base_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('sig_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('d_signal', models.CharField(blank=True, max_length=1000, null=True)),
                ('e_p_signal', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('fmt', models.CharField(blank=True, max_length=1000, null=True)),
                ('samps_per_frame', models.CharField(blank=True, max_length=1000, null=True)),
                ('skew', models.CharField(blank=True, max_length=1000, null=True)),
                ('byte_offset', models.CharField(blank=True, max_length=1000, null=True)),
                ('adc_gain', models.CharField(blank=True, max_length=1000, null=True)),
                ('baseline', models.CharField(blank=True, max_length=1000, null=True)),
                ('units', models.CharField(blank=True, max_length=1000, null=True)),
                ('adc_res', models.CharField(blank=True, max_length=1000, null=True)),
                ('adc_zero', models.CharField(blank=True, max_length=100, null=True)),
                ('init_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('checksum', models.CharField(blank=True, max_length=1000, null=True)),
                ('block_size', models.CharField(blank=True, max_length=1000, null=True)),
                ('has_annotations', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('mlii', models.FloatField()),
                ('v5', models.FloatField()),
                ('annotation', models.CharField(blank=True, max_length=10, null=True)),
                ('signal_record_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_record_name', to='patientdb.patient')),
            ],
        ),
    ]
