# Generated by Django 3.1.3 on 2020-11-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=100)),
                ('n_sig', models.CharField(max_length=100)),
                ('fs', models.CharField(max_length=100)),
                ('counter_freq', models.CharField(max_length=100)),
                ('base_counter', models.CharField(max_length=100)),
                ('sig_len', models.CharField(max_length=100)),
                ('base_time', models.CharField(max_length=100)),
                ('base_date', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('sig_name', models.CharField(max_length=100)),
                ('p_signal', models.CharField(max_length=100)),
                ('d_signal', models.CharField(max_length=100)),
                ('e_p_signal', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('fmt', models.CharField(max_length=100)),
                ('samps_per_frame', models.CharField(max_length=100)),
                ('skew', models.CharField(max_length=100)),
                ('byte_offset', models.CharField(max_length=100)),
                ('adc_gain', models.CharField(max_length=100)),
                ('baseline', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('adc_res', models.CharField(max_length=100)),
                ('adc_zero', models.CharField(max_length=100)),
                ('init_value', models.CharField(max_length=100)),
                ('checksum', models.CharField(max_length=100)),
                ('block_size', models.CharField(max_length=100)),
            ],
        ),
    ]
