# Generated by Django 3.1.6 on 2021-02-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientdb', '0003_auto_20210223_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signals',
            old_name='mlii',
            new_name='MLII',
        ),
        migrations.RenameField(
            model_name='signals',
            old_name='v5',
            new_name='V5',
        ),
    ]
