# Generated by Django 3.1.6 on 2021-02-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientdb', '0004_auto_20210223_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signals',
            old_name='MLII',
            new_name='mlii',
        ),
        migrations.RenameField(
            model_name='signals',
            old_name='V5',
            new_name='v5',
        ),
    ]
