# Generated by Django 3.1.7 on 2021-03-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientdb', '0006_auto_20210318_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signals',
            old_name='hannotation',
            new_name='annotation',
        ),
    ]
