# Generated by Django 3.1.7 on 2021-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdb', '0007_auto_20210318_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='has_annotations',
            field=models.BooleanField(default=False),
        ),
    ]
