# Generated by Django 3.1.3 on 2020-11-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('mlii', models.FloatField()),
                ('v5', models.FloatField()),
                ('signal_record_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_record_name', to='patientdb.patient')),
            ],
        ),
    ]
