# Generated by Django 3.1.3 on 2020-11-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrhythmias', '0002_usermodel_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
            ],
        ),
    ]
